### PR TITLE
Implement api-design v0.3.0

### PR DESCRIPTION
**Pull request by mcanoy**
#### What does this PR do?

Implements v0.3.0 - Changes to model
#### Which tests illustrate how this code works?

All of the many tests there are. But seriously, the engagement test shows the db persistence working
#### Is there a relevant Issue open for this?

n/a
#### Are there any other relevant resources that should be reviewed as well?

https://github.com/rht-labs/api-design from master but is v0.3.0. Tag coming soon.
#### Who would you like to review this?

/cc @mdanter @jholmes

### CODE REVIEW

**Comment by sherl0cks** [comment]
@mcanoy this fails my integration testing. I've deployed this out to the CDK using f-m-p. I posted [this json](https://gist.github.com/sherl0cks/f011e36dc4f1ccec65b6496be0782bd6), which appears to save fine. However; all GETs fail see the [error log](https://gist.github.com/sherl0cks/ac369908d4b4091a144aa91e4d214ab1)

**Comment by mcanoy** [comment]
@sherl0cks - Fixed issued with Route. PK definition in orm.xml was not compatible with String. Switch to Long in object. Opened issue in api-design to change the id definition of Route. - Added get tests for engagement

**Comment by sherl0cks** [comment]
@mcanoy @mdanter I've merged to move the ball forward, but left the issue open for a code review

**Comment by sherl0cks** [comment]
@mcanoy I'm getting a whole bunch of [duplicate data](https://gist.github.com/sherl0cks/c7802578c2d29a0817e1e56986cc4c1f) on GET /engagements/1. The GET /engagements looks fine

**Pull request merged**
